go_lint fixes
❯ make lint
golangci-lint run
WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
cmd/cloud-network-config-controller/main.go:187:21: Error return value of `signals.ShutDown` is not checked (errcheck)
                                signals.ShutDown()
                                                ^
pkg/cloudprovider/aws.go:337:3: S1011: should replace loop with `instances = append(instances, reservation.Instances...)` (gosimple)
                for _, instance := range reservation.Instances {
                ^
pkg/cloudprovider/cloudprovider.go:25:9: S1028: should use fmt.Errorf(...) instead of errors.New(fmt.Sprintf(...)) (gosimple)
        return errors.New(fmt.Sprintf("%s: %s", UnexpectedURIErrorString, uri))
               ^
pkg/cloudprovider/gcp.go:160:3: SA4004: the surrounding loop is unconditionally terminated (staticcheck)
                return []*NodeEgressIPConfiguration{config}, nil
                ^
pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go:232:7: SA4006: this value of `cloudPrivateIPConfig` is never used (staticcheck)
                        if cloudPrivateIPConfig, err = c.updateCloudPrivateIPConfigStatus(cloudPrivateIPConfig, status); err != nil {
                           ^
pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go:332:7: SA4006: this value of `cloudPrivateIPConfig` is never used (staticcheck)
                        if cloudPrivateIPConfig, err = c.updateCloudPrivateIPConfigStatus(cloudPrivateIPConfig, status); err != nil {
                           ^
make: *** [Makefile:22: lint] Error 1

Signed-off-by: Flavio Fernandes <flaviof@redhat.com>
Signed-off-by: Patryk Diak <pdiak@redhat.com>