SDN-5690:Rebase k8s to 1.32 Fix build error by passing in additional argument to function call.
	eventRecorder := events.NewKubeRecorder(kubeClient.CoreV1().Events(namespace), operatorName, &corev1.ObjectReference{
		APIVersion: "apps/v1",
		Kind:       "Deployment",
		Namespace:  namespace,
		Name:       deploymentName,
	}, passiveClock)

Build Error
----
CGO_ENABLED=0 GO111MODULE=on go build -mod vendor -o _output/bin/cloud-network-config-controller cmd/cloud-network-config-controller/main.go
cmd/cloud-network-config-controller/main.go:295:95: not enough arguments in call to events.NewKubeRecorder
	have ("k8s.io/client-go/kubernetes/typed/core/v1".EventInterface, string, *"k8s.io/api/core/v1".ObjectReference)
	want ("k8s.io/client-go/kubernetes/typed/core/v1".EventInterface, string, *"k8s.io/api/core/v1".ObjectReference, "k8s.io/utils/clock".PassiveClock)
make: *** [Makefile:2: build] Error 1
Use clock.RealClock{} instead of PassiveClock