go_lint fixes
❯ make lint 2>&1 | tee ~/xx
golangci-lint run
level=warning msg="[linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649."
pkg/controller/secret/secret_controller.go:68:43: Error return value of `(k8s.io/client-go/tools/cache.SharedInformer).AddEventHandler` is not checked (errcheck)
        secretInformer.Informer().AddEventHandler(cache.FilteringResourceEventHandler{
                                                 ^
pkg/controller/cloudprivateipconfig/cloudprivateipconfig_controller.go:87:57: Error return value of `(k8s.io/client-go/tools/cache.SharedInformer).AddEventHandler` is not checked (errcheck)
        cloudPrivateIPConfigInformer.Informer().AddEventHandler(cache.ResourceEventHandlerFuncs{
                                                               ^
pkg/controller/configmap/configmap_controller.go:68:46: Error return value of `(k8s.io/client-go/tools/cache.SharedInformer).AddEventHandler` is not checked (errcheck)
        configMapInformer.Informer().AddEventHandler(cache.FilteringResourceEventHandler{
                                                    ^
make: *** [Makefile:22: lint] Error 1

Signed-off-by: Flavio Fernandes <flaviof@redhat.com>